import {Link} from '@tanstack/react-router';
import {useState} from 'react';
import {UserRound,Package,MapPin,Heart,Bookmark,HelpCircle,Info,Settings,LogOut,ChevronRight,Instagram,MessageCircle,Clock,X,ArrowRight} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {products,money} from '@/data/shop';
import {useShop} from './store';
import {PageTitle,Empty} from './common';
import hero from '@/assets/baking-hero.jpg';
export function OrdersPage(){const {orders}=useShop();const [tab,setTab]=useState('All');const shown=orders.filter(o=>tab==='All'||o.status===tab);return <div className="content"><PageTitle title="My Orders" subtitle="A little baking joy, past and present"/><div className="filter-row">{['All','Processing','Shipped','Delivered'].map(t=><Button key={t} variant={tab===t?'default':'secondary'} className="filter-chip" onClick={()=>setTab(t)}>{t}</Button>)}</div>{shown.length?<div className="orders-grid">{shown.map(order=><article className="order-card" key={order.id}><div className="order-card-top"><div><h3>#{order.id}</h3><small>{order.date}</small></div><span className={`status-badge ${order.status.toLowerCase()}`}>{order.status}</span></div><div className="order-thumbs">{order.items.slice(0,4).map((item,i)=>{const p=products.find(p=>p.id===item.id);return p&&<img key={i} src={p.image} alt={p.name} width="60" height="60"/>})}</div><div className="order-card-bottom"><span>{order.items.length} items <strong className="ml-2">{money(order.total)}</strong></span><Link to="/order/$id" params={{id:order.id}}>View Details <ChevronRight size={13}/></Link></div></article>)}</div>:<Empty title="No orders here yet" description="Your next creation is waiting in the shop."/>}</div>}
export function ProfilePage(){const {setNotice}=useShop();const [modal,setModal]=useState(''),[address,setAddress]=useState(''),[saved,setSaved]=useState(false),[notifications,setNotifications]=useState(true),[signedOut,setSignedOut]=useState(false);return <div className="content"><div className="profile-layout"><div className="profile-header"><div className="avatar"><UserRound/></div><div><span>Hello,</span><h2>{signedOut?'Guest Baker':'Customer'}</h2><p>Your little baking world</p></div></div><div className="profile-menu">{[[Package,'My Orders','/orders'],[Heart,'Wishlist','/wishlist'],[Bookmark,'Saved Items','/wishlist'],[HelpCircle,'Help & Support','/contact'],[Info,'About Us','/about']].map(([Icon,label,to])=><Link to={to} key={label}><Icon size={18}/>{label}<ChevronRight size={16}/></Link>)}<Button variant="ghost" onClick={()=>setModal('My Addresses')}><MapPin size={18}/>My Addresses<ChevronRight size={16}/></Button><Button variant="ghost" onClick={()=>setModal('Settings')}><Settings size={18}/>Settings<ChevronRight size={16}/></Button><Button variant="ghost" onClick={()=>{setSignedOut(!signedOut);setNotice(signedOut?'Welcome back to your demo profile.':'You are now browsing as a guest.')}}><LogOut size={18}/>{signedOut?'Return to Demo Profile':'Logout'}<ChevronRight size={16}/></Button></div>{modal&&<div className="modal-backdrop"><div className="modal-box" role="dialog" aria-modal="true" aria-label={modal}><div className="modal-heading"><h2>{modal}</h2><Button size="icon" variant="ghost" onClick={()=>setModal('')} aria-label="Close dialog"><X/></Button></div>{modal==='My Addresses'?<><p className="mb-4 text-xs text-muted-foreground">{saved?'Your address has been saved for this visit.':'Add your delivery address.'}</p><textarea className="text-input" aria-label="Saved address" value={address} onChange={e=>setAddress(e.target.value)} placeholder="House number, street, city and PIN code"/><Button onClick={()=>{if(!address.trim()){setNotice('Please enter your address.');return}setSaved(true);setNotice('Address saved for this visit.')}}>Save Address</Button></>:<label className="option-card"><input type="checkbox" checked={notifications} onChange={e=>setNotifications(e.target.checked)}/>Order notifications <small>Demo preference</small></label>}</div></div>}</div></div>}
export function AboutPage(){return <div className="content"><div className="info-page"><PageTitle title="About DREAMS"/><img className="info-cover" src={hero} alt="Beautiful pink cake made with baking decorations" width="1536" height="1024"/><h2>DREAMS</h2><span className="eyebrow">BAKING SUPPLIES & MORE</span><p>Everything you need to bake better. DREAMS is a place for baking ingredients, cake decorations, thoughtful packaging and bakery supplies — the little essentials that help bring your creations to life.</p><p>From chocolate chips and cocoa powder to candles, cake boxes and piping tools, explore supplies for your everyday bakes and special celebrations.</p><Button asChild><Link to="/categories">Explore Our Categories <ArrowRight/></Link></Button></div></div>}
export function ContactPage(){return <div className="content"><div className="info-page"><PageTitle title="Let’s talk baking" subtitle="Contact DREAMS · Baking Supplies & More"/><div className="contact-grid"><div className="contact-card"><Instagram/><h3>Instagram</h3><a href="https://www.instagram.com/d_r_e_a_m_s_5661/" target="_blank" rel="noreferrer">@d_r_e_a_m_s_5661 ↗</a></div><div className="contact-card"><MessageCircle/><h3>WhatsApp</h3><p>Store WhatsApp number coming soon.</p></div><div className="contact-card"><MapPin/><h3>Visit our store</h3><p>Store address to be added.</p></div><div className="contact-card"><Clock/><h3>Business Hours</h3><p>Opening hours to be confirmed.</p></div></div></div></div>}
